
-----------------------------ADMIN------------------------------------------
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','Dashboard',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','RolePermission',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','ProjectPermission',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','UnitDetail',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','Template',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','Documents',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Admin/CFO','UnitBooking',1,0,1,1,0,1,1435984606)
---------------------------------Sales Manager--------------------------------------
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','Dashboard',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','RolePermission',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','ProjectPermission',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','UnitDetail',0,0,1,1,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','Template',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','Documents',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Sales Manager','UnitBooking',1,0,1,1,0,0,1435984606)


------------------------------------CRM----------------------------------------------
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','Dashboard',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','RolePermission',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','ProjectPermission',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','UnitDetail',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','Template',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','Documents',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('CRM','UnitBooking',1,0,0,1,0,1,1435984606)


--------------------------------------ACCOUNT-----------------------------------------------------------------
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','Dashboard',1,1,1,1,1,1,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','RolePermission',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','ProjectPermission',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','UnitDetail',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','Template',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','Documents',0,0,0,0,0,0,1435984606)
INSERT INTO ubmControlMaster(RoleName ,MenuType ,isTab,isCreate ,isEdit ,isView ,isDelete ,isApproved,GroupID)
VALUES('Account','UnitBooking',1,0,0,1,0,1,1435984606)


